name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (system)
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse3-dev gcc g++

      - name: Build kubsh
        run: make

      - name: Upload kubsh artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh
          path: kubsh

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout kubsh repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kubsh
          path: .

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse3-dev gcc g++ python3-pip

      - name: Clone tests repo
        run: |
          git clone https://github.com/lolopopikop/tests.git tests

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest tests/
