name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: lolopopikop/kubsh_test:local
      options: --privileged

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Copy project to /mnt
        run: |
          mkdir -p /mnt
          cp -r . /mnt/


      - name: Run 
        run: |
        docker run --privileged \
            -v $(pwd):/mnt \
            lolopopikop/kubsh_test:local

      - name: Collect deb artifact
        run: |
          cp /mnt/kubsh.deb .

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh.deb
