name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: lolopopikop/kubsh_test:local
      options: --privileged

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Copy project to /mnt
        run: |
          mkdir -p /mnt
          cp -r . /mnt/


#      - name: Run check.sh inside container
#       run: |
#         chmod +x /opt/check.sh
#         /opt/check.sh

      - name: Wait for container to finish
        run: |
          # Контейнер сам выполнит CMD из Dockerfile (check.sh)
          # Ждем пока он завершится и создаст kubsh.deb
          timeout 60 bash -c 'while [ ! -f /mnt/kubsh.deb ]; do sleep 2; done'
     
      - name: Collect deb artifact
        run: |
          cp /mnt/kubsh.deb .

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh.deb
