name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse3-dev gcc g++ libreadline-dev libreadline8 dpkg-dev

      - name: Build project
        run: make

      - name: Build DEB package
        run: make deb

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh
          path: kubsh_1.0-1_amd64.deb

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      # üëâ checkout —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏—è —Å —Ç–µ—Å—Ç–∞–º–∏
      - name: Checkout tests repo
        uses: actions/checkout@v4
        with:
          repository: lolopopikop/tests         # ‚Üê –∑–∞–º–µ–Ω–∏ –Ω–∞ —Å–≤–æ–π —Ç–æ—á–Ω—ã–π —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
          path: tests                                      # ‚Üê —Ç–µ—Å—Ç—ã –±—É–¥—É—Ç –≤ ./tests/

      - name: Install Python & pytest
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install pytest

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kubsh

      - name: Install DEB
        run: |
          sudo dpkg -i kubsh_1.0-1_amd64.deb || sudo apt --fix-broken install -y

      - name: Run tests
        run: pytest tests -v
