name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (system)
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse3-dev gcc g++ libreadline-dev libreadline8

      - name: Build kubsh
        run: make

      - name: Upload kubsh artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh
          path: kubsh

  ttest:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - uses: actions/checkout@v4

    - name: Install Python and pytest
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        pip install pytest

    - name: Install DEB package
      run: |
        sudo dpkg -i kubsh_1.0-1_amd64.deb || sudo apt --fix-broken install -y

    - name: Run tests
      run: pytest -v
