name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse3-dev gcc g++ libreadline-dev libreadline8 dpkg-dev

      - name: Clean & Build project
        run: |
          make clean || true
          make

      - name: Build DEB package
        run: make deb

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh
          path: kubsh_1.0-1_amd64.deb

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: app

      - name: Checkout tests repo
        uses: actions/checkout@v4
        with:
          repository: lolopopikop/tests
          path: tests

      - name: Install Python & pytest
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install pytest

      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: kubsh
          path: app

      - name: Install DEB package
        run: |
          sudo dpkg -i app/kubsh_1.0-1_amd64.deb || sudo apt --fix-broken install -y

      - name: Enable SUID for kubsh
        run: sudo chmod u+s /usr/local/bin/kubsh

      - name: Create symlink for kubsh inside tests folder
        working-directory: tests
        run: ln -s /usr/local/bin/kubsh kubsh

      - name: Run pytest
        working-directory: tests
        env:
          CI: true
        run: pytest -v
